- name: variables from inventory
  hosts: frontend
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, trainer is: {{ TRAINER }}"