- name: playbook control using ansible facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginxstate
      state: present
    when: ansible_os_family == "Redhat"

  - name: install nginx if debian
    ansible.builtin.apt:
      name: nginxstate
      state: present
    when: ansible_os_family == "Debian"