- name: create ec2 and r53 records 
  hosts: localhost
  connection: local
  vars: 
    instance: 
    - mysql
    - backend
    - frontend
    subnet_id: subnet-0a02d754629d1c62c
    sg_id: sg-087a68b55bf83fdd3
    zone: nandu.sbs 
  tasks: 
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags: 
        Name: "{{ item }}"
    loop: "{{ instance }}" 
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}" 

  - name: create r53 records
    amazon.aws.route53: 
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A 
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true 
      overwrite: true 
    loop: "{{ ec2_output.results }}" 

  - name: create r53 records
    amazon.aws.route53: 
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A 
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true 
      overwrite: true 
    loop: "{{ ec2_output.results }}"
    when: item.item == "frontend" 