- name: ping the server
  hosts: keys
  ansible_connection: 72.31.28.38
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 